AUTHORITY_SRCS_BY_RELATION: dict[str, list[str]] = {
    # Entertainment / arts
    "author": [
        "the Library of Congress",
        "the British Library",
        "the Pulitzer Prize committee",
        "a published bibliography",
        "the National Book Foundation",
        "the Oxford Reference",
        "the Encyclopedia Britannica",
    ],
    "composer": [
        "the Royal Academy of Music",
        "the Grammy Awards committee",
        "a musicology textbook",
        "the Berklee College of Music",
        "the International Music Council",
        "the Oxford Reference",
        "the Encyclopedia Britannica",
    ],
    "director": [
        "the Academy of Motion Picture Arts and Sciences",
        "the British Film Institute",
        "the Cannes Film Festival jury",
        "the Directors Guild of America",
        "the American Film Institute",
        "the Oxford Reference",
        "the Encyclopedia Britannica",
    ],
    "producer": [
        "the Academy of Motion Picture Arts and Sciences",
        "the British Film Institute",
        "the Producers Guild of America",
        "the Cannes Film Festival jury",
        "the American Film Institute",
        "the Oxford Reference",
        "the Encyclopedia Britannica",
    ],
    "screenwriter": [
        "the Writers Guild of America",
        "the Academy of Motion Picture Arts and Sciences",
        "the British Film Institute",
        "the Sundance Institute",
        "the American Film Institute",
        "the Oxford Reference",
        "the Encyclopedia Britannica",
    ],
    "genre": [
        "the Library of Congress",
        "a media studies textbook",
        "an arts encyclopedia",
        "a cultural database",
        "the Oxford Reference",
        "the Encyclopedia Britannica",
        "a reference catalog",
    ],
    # Geography / politics
    "capital": [
        "the CIA World Factbook",
        "the United Nations",
        "National Geographic",
        "an official government atlas",
        "the World Atlas",
        "the Oxford Reference",
        "the Encyclopedia Britannica",
    ],
    "country": [
        "the CIA World Factbook",
        "the United Nations",
        "National Geographic",
        "an official government atlas",
        "the World Atlas",
        "the Oxford Reference",
        "the Encyclopedia Britannica",
    ],
    "place of birth": [
        "an official birth certificate",
        "a government census record",
        "the National Archives",
        "a published biography",
        "a civil registry",
        "the Oxford Reference",
        "the Encyclopedia Britannica",
    ],
    # Biographical / personal
    "father": [
        "a genealogical record",
        "an official birth certificate",
        "the National Archives",
        "a published biography",
        "a civil registry",
        "the Oxford Reference",
        "the Encyclopedia Britannica",
    ],
    "mother": [
        "a genealogical record",
        "an official birth certificate",
        "the National Archives",
        "a published biography",
        "a civil registry",
        "the Encyclopedia Britannica",
    ],
    "occupation": [
        "a published biography",
        "the Oxford Reference",
        "the Encyclopedia Britannica",
    ],
    "religion": [
        "a census record",
        "a published biography",
        "the Pew Research Center",
        "an official church registry",
        "the Oxford Reference",
        "the Encyclopedia Britannica",
    ],
    "sport": [
        "the International Olympic Committee",
        "a sports federation record",
        "the Associated Press",
        "a Hall of Fame registry",
        "the Oxford Reference",
        "the Encyclopedia Britannica",
    ],
    # Properties
    "color": [
        "a design specification sheet",
        "a museum catalog",
        "an official product catalog",
        "a manufacturer's specification",
        "the Oxford Reference",
        "the Encyclopedia Britannica",
    ],
}

BELIEF_SRCS = [
    "my neighbor",
    "my colleague at work",
    "a stranger on the bus",
    "my uncle",
    "a friend of mine",
    "someone I met at a party",
    "my old roommate",
    "a taxi driver",
    "a guy at the gym",
    "my dentist",
]
